### ISSUE TITLE
Consider additional options for AddSqlDataSource

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlClientExtensions#3]
See https://github.com/npgsql/npgsql/blob/main/src/Npgsql/NpgsqlDataSourceBuilder.cs

**Comment by roji** [comment]
Do you have anything specific in mind that you can do here without actual support from SqlClient itself? For example, you're not going to be able to enable logging support unless SqlClient adds that...

**Comment by ErikEJ** [comment]
If you could look at the readme that would be great. Logging is there shoehorned in...

**Comment by ErikEJ** [comment]
Also your opinion if this adds value as is.

**Comment by roji** [comment]
Oh wait, I think I missed that... But can you point me to where you actually make SqlClient log via the provided ILoggerFactory?

**Comment by roji** [comment]
Ah I think I understand - [is this it](https://github.com/ErikEJ/SqlClientExtensions/blob/main/src/SqlClientExtensions/SqlLoggingConfiguration.cs#L19)? Does this magically route SqlClient tracing into the ILoggerFactory somehow? I wasn't aware of this thing ([docs](https://docs.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver16)).

/cc @ajcvickers

**Comment by ErikEJ** [comment]
>> Does this magically route SqlClient tracing into the ILoggerFactory somehow?

Yes, via this class: https://github.com/ErikEJ/SqlClientExtensions/blob/main/src/SqlClientExtensions/SqlClientListener.cs

**Comment by ErikEJ** [comment]
Took me a few attempts 🐑
